# ==== Phase 1 : Builder ====
FROM node:24-bullseye AS builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=2048"

COPY package*.json ./

RUN npm ci

COPY . .
COPY prisma ./prisma

RUN npx prisma generate

RUN npm run build


# ==== Phase 2 : Image finale légère ====
FROM node:24-bullseye

WORKDIR /app

ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=512"
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/ ./

COPY --from=builder /app/ ./

# --- SÉCURITÉ : UTILISATEUR NON-ROOT ---
# 1. Créer un groupe et un utilisateur système dédiés
RUN groupadd -g 1001 nodejs && \
    useradd -u 1001 -g nodejs -s /bin/sh nextjs

# 2. Transférer la propriété du dossier /app à cet utilisateur
RUN chown -R nextjs:nodejs /app

# 3. Basculer sur l'utilisateur non-privilégié
USER nextjs
# ---------------------------------------

EXPOSE 4004

CMD ["npm", "start"]