CREATE TYPE "ShippingStatus" AS ENUM ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERING', 'DELIVERED', 'CANCELLED');

ALTER TABLE "Order" ADD COLUMN "shippingStatus" "ShippingStatus" NOT NULL DEFAULT 'PENDING';
